main: com.stardevllc.starwarps.plugin.StandaloneStarWarpsPlugin
version: ${version}
api-version: 1.13
name: ${rootProject.name}
author: Firestar311
softdepend: [PlaceholderAPI]
commands:
  delwarp:
  warp:
  renamewarp:
  setwarp: