main: com.stardevllc.starwarps.StarWarpsPlugin
version: ${version}
api-version: 1.13
name: ${rootProject.name}
author: Firestar311
depend: [StarCore]
softdepend: [PlaceholderAPI]
commands:
  delwarp: 
  warp: 
  renamewarp:
  setwarp: